language: node_js
node_js:
- node

env:
- PLATFORM=CHROME
install:
- npm install
- npm install -g cucumber
- npm install --save-dev cucumber@latest selenium-webdriver@3.0.1
- npm install chromedriver

script:
  - npm test
notifications:
  email:
    recipients:
      - lam0196vn@gmail.com
    on_success: never
    on_failure: always
